### ISSUE TITLE
Add Warning Against Storing Twitter API Keys and Secrets in Source Files

### ISSUE THREAD

**Issue by ardalis** [dotnet-presentations/blazor-workshop#114]
In https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/06-authentication-and-authorization.md it sets up Twitter but doesn't caution the reader/user against storing their own twitter keys in a plain text file that is put in source control. They shouldn't do this in a real app and the workshop should warn against this practice.

**Comment by danroth27** [comment]
The Twitter auth flow has been replaced with the built-in auth support using ASP.NET Core Identity + IdentityServer.
