### ISSUE TITLE
Embedded Resources not shown in project file

### ISSUE THREAD

**Issue by ardalis** [dotnet-presentations/blazor-workshop#115]
In step 7 of the workshop it says:

>  If you peek inside of the project file for the ComponentsLibrary you'll see that the files in the content directory are built into the library as embedded resources.

But if you look at the project file there's nothing there about embedded resources:

![image](https://user-images.githubusercontent.com/782127/60361294-d98f1100-99ab-11e9-99d5-342a62934bfc.png)

**Comment by danroth27** [comment]
Hi @ardalis! It looks like this text is no longer used in the workshop, so I'm going to go ahead and close this. Thanks for trying Blazor!
