### ISSUE TITLE
editform

### ISSUE THREAD

**Issue by kouroshsalahshoor** [dotnet-presentations/blazor-workshop#124]
<EditForm Model="@OrderState.Order" OnValidSubmit="@PlaceOrder">
should be:
<EditForm Model="@OrderState.Order.DeliveryAddress" OnValidSubmit="@PlaceOrder">

**Comment by yopez83** [comment]
What is the issue about?

**Comment by yopez83** [comment]
@kouroshsalahshoor I guess you can close this issue as no relevant information was provided
