### ISSUE TITLE
Blazor.MonoRuntime.targets error code -532462766

### ISSUE THREAD

**Issue by XeroPhane** [dotnet-presentations/blazor-workshop#126]
This section of Blazor.MonoRuntime.targets is problematic and unstable.
`
    <Exec Command="dotnet &quot;$(MonoLinkerPath)&quot; $(_BlazorLinkerAdditionalOptions) @(_BlazorFolderLookupPaths, ' ') -o &quot;$(BlazorIntermediateLinkerOutputPath)&quot; @(_BlazorAssemblyDescriptorFiles, ' ') @(_BlazorAssembliesToLink, ' ')"  />`

I'm not sure if it's an issue related to .NET, Blazor, Preview 6/7, or Entity Framework.  It seems to happen after installing EF as in the top side of this article:
https://code.msdn.microsoft.com/Creating-An-SPA-Using-0b76bd13

Sometimes the solution will build and launch fine, sometimes it won't and it produces this error:

> MSB3073	The command [the result of everything pasted above] exited with code -532462766.

I'll restart VS and sometimes it builds fine, sometimes it doesn't.

**Comment by kaanlab** [comment]
This link is out of date.
You shoud follow this instruction https://docs.microsoft.com/ru-ru/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by XeroPhane** [comment]
Is there anything on there about connecting to SQL?

**Comment by XeroPhane** [comment]
To clarify my post, the area in that link I'm referring to is:
[At package manager console]

Install-Package Microsoft.EntityFrameworkCore.SqlServer

Install-Package Microsoft.EntityFrameworkCore.Tools

Scaffold-DbContext "Your connection string here" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables Employee

**Comment by XeroPhane** [comment]
I commented out the subject line in Blazor.MonoRuntime.targets and everything builds and runs without issues so far.  Is this line critical?

**Comment by AkumaKHI** [comment]
I was having the same problem when working with Telerik UI component. I got the solution from [Telerik docs](https://docs.telerik.com/blazor-ui/getting-started/client-blazor#set-up-a-blazor-project).

Open the Client .csproj file and ensure that the following switch is present. At the moment the IL Linker needs to be disabled because of [an issue in Mono.](https://github.com/mono/mono/issues/12917)
`<PropertyGroup>
    
    <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>`

This certainly fixed the problem. hope it will help to others as well (even if they're not using Telerik UI)

**Comment by msollicito** [comment]
Install the latest visual studio 2019 preview - then reboot and delete all in bin and obj before rebuilding
- that fixed this for me -

**Comment by danroth27** [comment]
Everything should be working now with the latest bits and workshop updates. Let us know though if you're still hitting issues!
