### ISSUE TITLE
SQLite database provider for EF Core 3.0.0-preview7.19362.6 does not work correctly

### ISSUE THREAD

**Issue by kaanlab** [dotnet-presentations/blazor-workshop#127]
I update all solution to 3.0.0-preview7. When i make a request in MyOrders.razor to `HttpClient.GetJsonAsync<List<OrderWithStatus>>("orders");`
GetOrders() action in OrdersController does not include data for DeliveryLocation property.
In preview6 everything is fine.

**Comment by EdCharbeneau** [comment]
Related or duplicate issue: https://github.com/dotnet-presentations/blazor-workshop/issues/95

**Comment by EdCharbeneau** [comment]
Temporary fix is to rollback to Preview 6. Seems like a regression in SqlLite provider.

**Comment by danroth27** [comment]
Everything should be working now with the latest bits and workshop updates. Let us know though if you're still hitting issues!
