### ISSUE TITLE
For preview7 need to update RCL static asset path

### ISSUE THREAD

**Issue by kaanlab** [dotnet-presentations/blazor-workshop#129]
RCL are changed in preview7 https://github.com/aspnet/AspNetCore.Docs/pull/13501/files need to update index.html 
`
    <script src="_content/Blazingpizza.ComponentsLibrary/localStorage.js"></script>
    <script src="_content/Blazingpizza.ComponentsLibrary/deliveryMap.js"></script>
    <script src="_content/Blazingpizza.ComponentsLibrary/leaflet/leaflet.js"></script>
`

**Comment by EdCharbeneau** [comment]
@kaanlab Thanks! I was trying to figure out what went wrong.

**Comment by danroth27** [comment]
Thanks for bringing this to our attention! The latest version of the workshop has these changes.
