### ISSUE TITLE
$(AspNetCoreVersion) not updated after preview7 install

### ISSUE THREAD

**Issue by nicothenico** [dotnet-presentations/blazor-workshop#130]
When doing a clean checkout, after I installed preview7, I get the following error when building BlazzingPizza.Client project because $(AspNetCoreVersion) looks to still be pointing to preview6 (from VS Solution Explorer Dependencies).

> obj\Debug\netstandard2.0\Razor\Shared\ConfigurePizzaDialog.razor.g.cs(126,21): error CS1061: 'RenderTreeBuilder' does not contain a definition for 'SetUpdatesAttributeName' and no accessible extension method 'SetUpdatesAttributeName' accepting a first argument of type 'RenderTreeBuilder' could be found (are you missing a using directive or an assembly reference?)

dotnet --list-sdks:
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.800 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

Had to explicitly specify the version number instead of using $(AspNetCoreVersion) in the .csproj to make the project build successfully:
From:
`
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="$(AspNetCoreVersion)" PrivateAssets="all" />    
  </ItemGroup>`

To:
`<ItemGroup>
     <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
     <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" PrivateAssets="all" />    
   </ItemGroup>`

**Comment by simondahlstrom** [comment]
Nice catch! Solved my issues.

**Comment by zvinch** [comment]
This  also solved my issue that manifested as an error:
`EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0,  `

It seems that `$(AspNetCoreVersion)` should be controlled through [Directory.Build.props](https://github.com/dotnet-presentations/blazor-workshop/blob/1c35728a9cafb1add72e14fae88dd037216913d7/Directory.Build.props) in the root of this repo. However it is unclear to me which versions should be put there.  
Setting it to "3.0.0-preview7.19365.7" result in yet another build failure.

**Comment by rynowak** [comment]
This has since been updated a few times. If anyone is still stuck please open a new issue.
