### ISSUE TITLE
Display Orders in MyOrders Page failed

### ISSUE THREAD

**Issue by Mark-Phillipson** [dotnet-presentations/blazor-workshop#132]
I had to make a change to the Orders class to give the DeliveryLocation a default value, otherwise the orders were not being returned an error of object not set was occurring.

As per the following:

```
public LatLong DeliveryLocation { get; set; } = new LatLong
        {
            Latitude= 1000,Longitude= 1000
        }; screen
```

**Comment by yopez83** [comment]
This issue shouldn't have happened, since the `PlaceOrder` action from `OrdersController` in line 78 is defaulting the delivery location to lat=51.5001 long=-0.1239

**Comment by danroth27** [comment]
Closing, as the latest version of the workshop should not have this issue.
