### ISSUE TITLE
is OnInitAsync() still a thing?

### ISSUE THREAD

**Issue by smwentum** [dotnet-presentations/blazor-workshop#135]
I was working through the workshop and in part 2 where I am supposed to add the toppings it says use

 `protected async override Task OnInitAsync()
    {
        toppings = await HttpClient.GetJsonAsync<List<Topping>>("toppings");
    }`

but when i tried it i kept getting the error that there was nothing for OnInitAsync() to override, i just ended up chaning it to OnInitializedAsync() and that seemed to work

**Comment by salmanmkc** [comment]
As you mentioned, it seems to be OnInitializedAsync() that works now instead of OnInitAsync(), it will return the error that OnInitAsync() has no method to override

**Comment by uwerichter** [comment]
Says somewhat like Namespacename "Layouts" not in "Microsoft.AspNetCore.Components"

**Comment by salmanmkc** [comment]
> Says somewhat like Namespacename "Layouts" not in "Microsoft.AspNetCore.Components"

You need to remove that reference as well, no longer needed

**Comment by nicothenico** [comment]
The change to OnInitializedAsync() was listed in the article for upgrading from preview 7 to 8.
[https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/](url)

> In Razor components rename OnInit to OnInitialized and OnInitAsync to OnInitializedAsync.

**Comment by yopez83** [comment]
Use OnInitializedAsync() instead

**Comment by rynowak** [comment]
Closing as answered
