### ISSUE TITLE
Error using local storage

### ISSUE THREAD

**Issue by yopez83** [dotnet-presentations/blazor-workshop#136]
When implementing "Preserving order state across the redirection flow" from "06-authentication-and-authorization" module. The application stopped displaying the Checkout component. When I opened Chrome's developer console see below the error I see.

![localstorage_error](https://user-images.githubusercontent.com/12285372/63795303-ac8aac00-c8d1-11e9-998e-3dd9bab49364.png)

**Comment by albilaga** [comment]
Try change in BlazingPizza.Client in wwwroot folder index.html and replace _content/blazingpizzacomponentslibrary to _content/BlazingPizza.ComponentsLibrary. Will do PR though maybe

**Comment by yopez83** [comment]
It works. Thank you.
