### ISSUE TITLE
Building for the first time errors

### ISSUE THREAD

**Issue by jameka23** [dotnet-presentations/blazor-workshop#139]
Hey is there a reason that I'm getting 

"The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?"

got this thrown from line 20 in Startup.cs in the Configure() method.

**Comment by rafaelmalheiros** [comment]
There are some breaking changes for preview 9.
Working on fixes.
Check #141 for updates.

**Comment by danroth27** [comment]
Should be fixed now.
