### ISSUE TITLE
Update do Preview 9

### ISSUE THREAD

**Issue by rafaelmalheiros** [dotnet-presentations/blazor-workshop#141]
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/

**Comment by Walad100100** [comment]
Kindly, please update the tutorial to Preview 9. I am using it in the classroom and all stopped working as Visual Studio forced us to update to Preview 9.

Thanks!

**Comment by SunXnuS** [comment]
Any idea when the update will happen?

**Comment by rafaelmalheiros** [comment]
> Any idea when the update will happen?

There is some PR to fix it, but I guess they are waiting for the final release next week,

**Comment by rafaelmalheiros** [comment]
.Net Core 3.0 is now GA and the application should be updated to that.
