### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by worthingtonjg** [dotnet-presentations/blazor-workshop#145]
I am on the last step in the tutorial - I am trying to get the Map component to work, but I am getting errors because the page can't find the deliveryMap.js, localStorage.js, leaflet,css, or leaflet.js.

Those are all in the wwwroot folder of the BlazingPizza.ComponentsLibrary project, but I don't see how they make into the client?  

Also the index.html in the client is looking for these to be in an _content folder.

Did something change?  It seems like something is missing here.  

I can actually get it to work if I manually copy everything into the Client project, but was wondering how to get it to work without ding that.  

The rest of the tutorial is great - all the steps work wonderfully - thanks for a well written great tutorial.

**Comment by LauriKat** [comment]
You need to change on BlazingPizza.Client>wwwroot>index.html  script sources to
    <script src="_content/Blazingpizza.ComponentsLibrary/localStorage.js"></script> 
    <script src="_content/Blazingpizza.ComponentsLibrary/deliveryMap.js"></script> 
    <script src="_content/Blazingpizza.ComponentsLibrary/leaflet/leaflet.js"></script>

**Comment by SteveSandersonMS** [comment]
Thanks for answering, ghost!
