### ISSUE TITLE
Page not shown correctly

### ISSUE THREAD

**Issue by HaraldurSam** [dotnet-presentations/blazor-workshop#147]
After updating the project files to v9 of blazor, I managed to compile and run the projects.

Running the very first step should show a webpage with the words "Blazing Pizzas", but the only thing I get is running progress bar.
What could be wrong, why isn't the web page loading the index.razor page?

**Comment by dennml** [comment]
I have the same problem. Would really like to progress with my learning but haven't been able to get it running.

The words "Blazing Pizzas" should come from Index.razor

But instead it is loading Index.html which is the page with the progress bar.

The following line from Startup.cs in BlazingPizza.Server seems to cause this:
`endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");`

The name MapFallbackToClientSideBlazor suggests it is a fall back mechanism. 
If I comment out that line, I get a blank page, not "Blazing Pizzas"

Why is it not displaying index.razor?

I am running VS2019 16.4.0 Preview 2 which is .NET Core 3.1 Preview 1. 
Updated Nuget packages to 3.1.0-preview1.19508.20 except NETStandard.Library which is 2.0.3

**Comment by rynowak** [comment]
If you're still stuck on this, please check your browser console window. Error messages will go there. 

If this doesn't work, try creating a new Blazor webassembly project from the template - does that help?

**Comment by SteveSandersonMS** [comment]
Hopefully this is answered, so closing.
