### ISSUE TITLE
Build Error for first time

### ISSUE THREAD

**Issue by vishwanath-uppala** [dotnet-presentations/blazor-workshop#150]
The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)	BlazingPizza.ComponentsLibrary	~\blazor-workshop\save-points\00-Starting-point\BlazingPizza.ComponentsLibrary\obj\Debug\netstandard2.0\RazorDeclaration\Map\Map.razor.g.cs

**Comment by MonsterLlama** [comment]
I'm also hitting this :(

**Comment by muneebakhter** [comment]
Same

**Comment by Rugved** [comment]
I had the same error. This is what I did to fix:
- update to latest visual studio version (check update from help menu, they release minor version often)
- get latest code of pizza app. I saw the error in code base few days ago but looks like its fixed when I took latest code today.

**Comment by rynowak** [comment]
Closing this since the workshop was just updated this morning. If you're having issues please make sure you have VS 16.3 and .NET Core SDK 3.0.100 (current as of time of writing).

**Comment by mbnoimi** [comment]
I've same problem with:
* dotnet 5.0.202
* Linux Mint 20.1
* Visual Studio Code 1.55.2
