### ISSUE TITLE
override intellisense 

### ISSUE THREAD

**Issue by SunXnuS** [dotnet-presentations/blazor-workshop#152]
Hi,

The intellisense for _override_ doesn't work if the keyword _async_ is declared before it.  For example:

if you type _protected override_ in the editor, all overridable methods will show.  However, if you type _protected async override_, you get no intellisense.

Thanks,

Billy

**Comment by SteveSandersonMS** [comment]
@NTaylorMullen Do you know if this is a known issue?

**Comment by NTaylorMullen** [comment]
Hmm, this works for me:

![image](https://i.imgur.com/F44AM0B.gif)

**Comment by SteveSandersonMS** [comment]
@NTaylorMullen Does it work if you type async before override? Is that legal? (On phone, can’t check right now)

**Comment by NTaylorMullen** [comment]
Doesn't work if you do `async` before but that's because C# doesn't support that in normal C# files either.

**Comment by SteveSandersonMS** [comment]
Thanks for checking! Not a bug then - will close.
