### ISSUE TITLE
MicrosoftAccount authentication not working

### ISSUE THREAD

**Issue by drakeforte5** [dotnet-presentations/blazor-workshop#157]
I tried to modify this to use MicrosoftAccountDefaults.AuthenticationScheme but it does not work.

Updated the Startup.cs to 
`                 .AddMicrosoftAccount(microsoftOptions =>
                 {
                     microsoftOptions.ClientId = Configuration["Authentication:Microsoft:ClientId"];
                     microsoftOptions.ClientSecret = Configuration["Authentication:Microsoft:ClientSecret"];
                     microsoftOptions.CallbackPath = "/";
                 });`

And the UserController.cs.SignIn to:

` await HttpContext.ChallengeAsync(MicrosoftAccountDefaults.AuthenticationScheme);`

Of course I had a client id and client secret on the Azure side but I can't get progress on it.

Does this now work with MS auth scheme?

Thanks.

**Comment by drakeforte5** [comment]
This won't work and the OpenId route should be implemented instead.

**Comment by Ricardoaraujo00** [comment]
How can we change the authentication to use google or facebook?

**Comment by yopez83** [comment]
@drakeforte5 this should help https://www.youtube.com/watch?v=v2OsI7qJdoc&list=PLdo4fOcmZ0oWlP1Qpzg7Dwzxr298ewdUQ&index=11&t=0s

**Comment by Ricardoaraujo00** [comment]
Thank you @yopez83 . Really fresh video.  I'm sure it will help!
