### ISSUE TITLE
Architecture Concern

### ISSUE THREAD

**Issue by nolisj** [dotnet-presentations/blazor-workshop#159]
Hi! I'm just wondering, on the architecture side of the application, why the BlazingPizza.Server is dependent on the BlazingPizza.Client? 

When you look at the code, you'll see that what connects the server to the client is in the Server's Startup.Configure function:

`app.UseClientSideBlazorFiles<Client.Startup>();`  //line 70; Client.Startup refers to the BlazingClient project; 

and here:

`endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");`  //line 75

Isn't this is a breakdown in the fundamental architectural design tenet where server code should not be calling client code?

Looking forward to the resolution of this concern.

**Comment by mrpmorris** [comment]
In a server-side blazor app the "client" is just the UI layer. Initializing UI services is normal in a server bootstrap because it runs inside the server app.

**Comment by yopez83** [comment]
If I'm not mistaken the solution has both Blazor hosting models, WebAssembly and Server. 
- If you run the Client project you're using the WebAssembly hosting model, please note you're running on IISExpress.
- If you run the Server project you still see the UI (Client), but notice there is a Console (Kestrel) application running in the back. Line 70 is just bootstrapping the UI.

**Comment by SteveSandersonMS** [comment]
Yes, the server's reference to the client is just to imply that the server has to build and publish the client too.

As it happens, we're about to eliminate this requirement in the next preview of Blazor WebAssembly (as in, the reference will be optional).

**Comment by green1971weekend** [comment]
For those who also confused in architecture layers as I was

https://stackoverflow.com/questions/58093386/whats-the-difference-between-asp-net-core-hosted-and-server-side-blazor-really
