### ISSUE TITLE
Debugging concern

### ISSUE THREAD

**Issue by geeForceOne** [dotnet-presentations/blazor-workshop#165]
Hi

First of all, thanks for this workshop. It's really great go get into the basics of blazor.

So I'm working on chapter 5 (validations) and I did a mistake when adapting the code. I had

`<InputText @bind="Address.Name" />`

instead of 
`<InputText @bind-Value="Address.Name" />`

and then when i was trying to navigate to /checkout the page stuck and by looking at the network and at the console output i didn't find and hint that the issue is with component AddressEditor.

Did I miss a place to look that could tell me more? If not how to debug such  issues?

Thanks
Giuseppe

**Comment by danroth27** [comment]
This issue was moved to dotnet/aspnetcore#20056
