### ISSUE TITLE
Documentation issue: Directory.build.props required

### ISSUE THREAD

**Issue by csharpfritz** [dotnet-presentations/blazor-workshop#172]
For workshop participants who copy the 00-Starting-Point folder to another location on their workstation, the Directory.build.props file needs to be copied into the folder next to the solution file in order to ensure that all projects get the appropriate ASP.NET Core and Blazor versions.

**Comment by danroth27** [comment]
Fixed by https://github.com/dotnet-presentations/blazor-workshop/commit/d40e16d82fad2fcac561a3b7e70f4a873cc82291
