### ISSUE TITLE
Checkout with Validation

### ISSUE THREAD

**Issue by krchome** [dotnet-presentations/blazor-workshop#173]
In this part,  these two classes named "checkout-delivery-address" and "checkout-order-details" for the Checkout.razor component are missing in the BlazingPizza solution that I have started doing with Save Points and reached this part 5 following the doc: 
So this is my own classes for the above missing ones:

```
checkout-order-details {
    overflow-y: auto;
    padding: 1.5rem 3rem;
    flex-grow: 1;
    padding: 12px;
    box-sizing: border-box;
}
.checkout-delivery-address {
    box-sizing: border-box;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
}
```

I thought that someone who's stuck with a similar situation could benefit from the classes.

**Comment by danroth27** [comment]
Thanks @krchome! As far as I can tell thought the styling looks ok without these additions so I think we'll just leave things as is.
