### ISSUE TITLE
Could anyone tell me why use HttpClient and Controller instead of call Backend Service directly?

### ISSUE THREAD

**Issue by andy65007** [dotnet-presentations/blazor-workshop#175]

**Comment by mrpmorris** [comment]
If it's server side only then there is no need.

**Comment by andy65007** [comment]
thanks a lot.

**Comment by rynowak** [comment]
This workshop uses Blazor web assembly which runs directly in the browser. So there's no ability to call into the database directly because you're running on some users' computer somewhere.
