### ISSUE TITLE
Templated Components Part - Error in Documentation 

### ISSUE THREAD

**Issue by krchome** [dotnet-presentations/blazor-workshop#176]
At **Adding a reference to the templated library** section kindly correct the sentence "Do this by adding a project reference from BlazingPizza.Client to BlazingComponents." to 
"Do this by adding a project reference to BlazingPizza.Client from BlazingComponents."

**Comment by SteveSandersonMS** [comment]
It's already correct. The reference goes *from* BlazingPizza.Client *to* BlazingComponents, not the other way round.
