### ISSUE TITLE
server side slider component

### ISSUE THREAD

**Issue by mselinger75** [dotnet-presentations/blazor-workshop#178]
I have a question about implementation details of a slider component. Let say i have a code like

`<div class="form-group"><label for="creditCardDebt" class="main__form-label">Credit Card Debt</label>	<span>		@ApplyFormModel.Debt.ToString("C")	</span>       <input type="range" min="0" max="30000" step="1000" id="creditCardDebt"                  class="form-control" @bind="@ApplyFormModel.Debt" @bind:event="oninput" /></div>`

So when using Blazor server side every time i move a slider to another position i see a request to the server. Could it be a potential performance issue? Any best practices on how to implement such use case in a different manner? Thanks!

**Comment by mrpmorris** [comment]
If you use JavaScript it will run in the browser, you could then have it call a SetValue method on your control either when you finish adjusting the scroller, or you could call it on every change but debounce it to keep the number of calls low.

**Comment by mselinger75** [comment]
thanks for your response! what i don't quite understand then is what is difference between my example and a standard Blazor Counter example? Counter example doesn't generate server side roundtrips in order to update the UI. Could the reason be because i have my range input inside EditForm tag?

**Comment by mrpmorris** [comment]
> 
> 
> thanks for your response! what i don't quite understand then is what is difference between my example and a standard Blazor Counter example? Counter example doesn't generate server side roundtrips in order to update the UI. Could the reason be because i have my range input inside EditForm tag?

If it is a server-side Blazor app then it absolutely does send an event to the server and receive updated HTML.

If you install the latest version of FireFox (version 72), open developer tools (F12), look in the Network tab, then reload your page, you'll see an item in the list with a response code 101. Click that, then look for the 'WS' option where the formats are listed, then click the Messages tab on the very right.

You'll now be able to watch messages out / in.

**Comment by mselinger75** [comment]
yes, i do see 101 when page loads for the first time. but after that when i click a button and counter increases there are no new networks requests.

**Comment by mselinger75** [comment]
i am sorry, my bad, i do see messages.

**Comment by mrpmorris** [comment]
> i am sorry, my bad, i do see messages.

The 101 connection remains open. Messages are exchanged via that.

**Comment by yopez83** [comment]
The 101 is the WebSocket connection being used by SignalR to communicate back and forth.

**Comment by mselinger75** [comment]
I know this is not related but maybe you can point me to the right direction. Let say i have a long form, and after validation i want to show summary of all errors above the form like:

@if (ShowErrors)
					{
						<div class="alert alert-danger" role="alert" id="errors">
							@foreach (var error in Errors)
							{
								<p>@error</p>
							}
						</div>
					}

The problem is because the form is really long one, errors div is not in a scroll view, so i want to scroll screen up to that div #errors. I can easily run via JS interop 

var element = document.getElementById(elementId);
element.scrollIntoView();

my problem is i don't know when Blazor finished updating a DOM and rendering #errors div, so i call scrollIntoView too early which obviously scrolls to the wrong position. Any way i can catch an event when Blazor finishes DOM update?

Thanks!

**Comment by yopez83** [comment]
@mselinger75 if the errors you want to display are related to the form data entry. I would rather use data annotations. You get a better UX, like:
- Displaying error messages below the element it belongs to.
- Error messages and elements are styled red.
- In the same token, valid entries are styled green.
If you want to try it, just change your form to `EditForm`. Your input to `InputText` -there are more-. Don't forget to add `<DataAnnotations />` to the end but before closing the EditForm. For more details check this out https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-checkout-with-validation.md#capturing-the-delivery-address

**Comment by mselinger75** [comment]
@yopez83 thanks for the response. the problem is i can't use data annotations for validation because i have a complex validation rules which makes calls to SQL database. That's why i prefer to use FluentValidation package and display error messages then.

**Comment by yopez83** [comment]
@mselinger75 why don't you try the following. Let's say after you do the validation you add the errors to the Model. Followed by calling `StateHasChanged()`, which will cause your UI to render the diff. Then, make sure at the end of `OnInitializedAsync()` you have a call to the following extension method (you have to create)
```csharp
    public static class JSRuntimeExtensions
    {
        public static ValueTask<bool> ScrollToElementById(this IJSRuntime jsRuntime, string elementId)
        {
            return jsRuntime.InvokeAsync<bool>("scrollToElementById", elementId);
        }
    }
```
Lastly make sure you have this function as well.
```javascript
        window.scrollToElementId = (elementId) => {
            var element = document.getElementById(elementId);
            if(element)
            {
                element.scrollIntoView();
                return true;
            }
            return false;
        }
```
See if that helps.

**Comment by SteveSandersonMS** [comment]
Hopefully the question is answered.

**Comment by mselinger75** [comment]
Thank you guys! StateHasChanged method did the trick, so my code looks like

if (ShowErrors)
		{
			StateHasChanged();
			await JsRuntime.ScrollToElementId("div-errors");
		}

my question though - how can i make sure that call to StateHasChanged re-renders component fast enough so by the time JsRuntime.ScrollToElementId executes my errors div already in place?

**Comment by mselinger75** [comment]
Also, even while using recommended approach for Blazor with EditForm and data annotation. Let say i have a really long form with 20 fields which i open on a mobile device. when i reach last field and submit button my top fields obviously scrolled out of the screen view. So even if i display error message after each form field there is no way to see them until i manually scroll back to the top of the from. Maybe any suggestions? Thanks!

**Comment by yopez83** [comment]
> my question though - how can i make sure that call to StateHasChanged re-renders component fast enough so by the time JsRuntime.ScrollToElementId executes my errors div already in place?

For more details on the Blazor Components Lifecycle click [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1). To answer your question, I'd override the `OnAfterRenderAsync()` and make the call to scroll there. Remember the call to `StateHasChanged()` should happens in the method you are making a request to the server.

**Comment by mselinger75** [comment]
thanks. i have already tried to use OnAfterRenderAsync and it worked just fine even without StateHasChanged call at all

protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		if (firstRender == false)
		{
			if (ShowErrors)
				await JsRuntime.ScrollToElementId("div-errors");
		}
	}
