### ISSUE TITLE
Custom event between components

### ISSUE THREAD

**Issue by yopez83** [dotnet-presentations/blazor-workshop#180]
As of now, the OrderDetails.razor component re-renders once the Status an order changes. However, the order status displayed at MyOrders.razor is not re-render unless I do F5. I wanted to implement such behavior, and after many attempts none seems to work. See below my changes.

**OrderState.cs**
`public event Action OnStatusChanged;`
`public void UpdateStatus() => OnStatusChanged?.Invoke();`

**OrderDetails.razor** 
I injected the `OrderState` so I could use it in the `PollForUpdates()` method. In that method before calling `StateHasChanged();`, I'm notifying the OrderState about an status change `OrderState.UpdateStatus();`

**MyOrder.razor**
I injected the `OrderState` as well, and added the `@implements IDisposable` directive. Below is my Dispose implementation.
`public void Dispose() => OrderState.OnStatusChanged -= Reload;`

This is my Reload method, which is just to notify the component has changed in order to re-render.
`private void Reload() => StateHasChanged();`

Here is my subscription to the `OrderState` event.
`protected override void OnInitialized() => OrderState.OnStatusChanged += Reload;`

Everything continues to work on the `OrderDetails.razor` component, but I still need to hit F5 to get the status to change.

**Comment by ADefWebserver** [comment]
Is the _Reload_ method being called in **MyOrder.razor**? If it is, call `StateHasChanged()` at the end of that method.

**Comment by yopez83** [comment]
@ADefWebserver, it is not being called anywhere else. I just use it to avoid calling directly the `StateHasChange()` , just in case I want to do something else later. But, even removing the method and subscribing the `StateHasChange()` did not work. I still get the `OrderDetails` component refreshing the status while `MyOrder` doesn't. In my code you see I'm using `Action` but even changing to `EventHandler` as in you blog, didn't work. I think it may have to do with the logic of the `PollForUpdates()`, but I'm just guessing.

**Comment by ADefWebserver** [comment]
> I think it may have to do with the logic of the `PollForUpdates()`, but I'm just guessing.

Yes, that must be it

**Comment by yopez83** [comment]
**OrderStatusNotifier**

```
namespace BlazingPizza.Client
{
    public class OrderStatusNotifier
    {
        public event EventHandler<OrderWithStatus> OnChanged;

        public void UpdateOrderStatus(OrderWithStatus orderWithStatus) => OnChanged?.Invoke(this, orderWithStatus);
    }
}
```

**OrderDetails.razor PollForUpdates() method**
```
    private async void PollForUpdates()
    {
        pollingCancellationToken = new CancellationTokenSource();
        while (!pollingCancellationToken.IsCancellationRequested)
        {
            try
            {
                invalidOrder = false;
                var currentStatus = orderWithStatus?.StatusText;
                orderWithStatus = await HttpClient.GetJsonAsync<OrderWithStatus>($"orders/{OrderId}");

                if (orderWithStatus.StatusText != currentStatus)
                {
                    OrderStatusNotifier.UpdateOrderStatus(orderWithStatus);
                }
            }
            catch (Exception ex)
            {
                invalidOrder = true;
                pollingCancellationToken.Cancel();
                Console.Error.WriteLine(ex);
            }

            StateHasChanged();

            await Task.Delay(8000);
        }
    }
```

**MyOrders.razor**
```
@code {
    List<OrderWithStatus> ordersWithStatus;

    protected override void OnInitialized() => OrderStatusNotifier.OnChanged += OnOrderStatusChanged;

    protected override async Task OnParametersSetAsync() => ordersWithStatus = await HttpClient.GetJsonAsync<List<OrderWithStatus>>("orders");

    void OnOrderStatusChanged(object sender, OrderWithStatus orderWithStatus)
    {
        var orderToUpdate = ordersWithStatus.FirstOrDefault(o => o.Order.OrderId == orderWithStatus.Order.OrderId);
        if (orderToUpdate == null)
        {
            return;
        }

        orderToUpdate.StatusText = orderWithStatus.StatusText;
        StateHasChanged();
    }

    public void Dispose() => OrderStatusNotifier.OnChanged -= OnOrderStatusChanged;
}
```

**Comment by ADefWebserver** [comment]
If `PollForUpdates()` is not called then that is why the whole thing wont work. Not sure what triggers `PollForUpdates()` ? Can you set a break point inside that method? Also, I would just call UpdateOrderStatus whenever an order chnages and not use  `PollForUpdates()` at all.

**Comment by yopez83** [comment]
@ADefWebserver my bad, this is all the code in `OrderDetails` component.
```
@page "/myorders/{orderId:int}"

@using System.Threading

@inject HttpClient HttpClient
@inject OrderStatusNotifier OrderStatusNotifier
@implements IDisposable

<div class="main">
    @if (invalidOrder)
    {
        <h2>Nope</h2>
        <p>Sorry, this order could not be loaded.</p>
    }
    else if (orderWithStatus == null)
    {
        <text>Loading...</text>
    }
    else
    {
        <div class="track-order">
            <div class="track-order-title">
                <h2>
                    Order placed @orderWithStatus.Order.CreatedTime.ToLongDateString()
                </h2>
                <p class="ml-auto mb-0">
                    Status: <strong>@orderWithStatus.StatusText</strong>
                </p>
            </div>
            <div class="track-order-body">
                <div class="track-order-details">
                    <OrderReview Order="@orderWithStatus.Order"/>
                </div>
            </div>
        </div>
    }
</div>

@code {
    [Parameter] public int OrderId { get; set; }

    OrderWithStatus orderWithStatus;
    bool invalidOrder;
    CancellationTokenSource pollingCancellationToken;

    protected override void OnParametersSet()
    {
        // If we were already polling for a different order, stop doing so
        pollingCancellationToken?.Cancel();

        // Start a new poll loop
        PollForUpdates();
    }

    private async void PollForUpdates()
    {
        pollingCancellationToken = new CancellationTokenSource();
        while (!pollingCancellationToken.IsCancellationRequested)
        {
            try
            {
                invalidOrder = false;
                var currentStatus = orderWithStatus?.StatusText;
                orderWithStatus = await HttpClient.GetJsonAsync<OrderWithStatus>($"orders/{OrderId}");

                if (orderWithStatus.StatusText != currentStatus)
                {
                    OrderStatusNotifier.UpdateOrderStatus(orderWithStatus);
                }
            }
            catch (Exception ex)
            {
                invalidOrder = true;
                pollingCancellationToken.Cancel();
                Console.Error.WriteLine(ex);
            }

            StateHasChanged();

            await Task.Delay(8000);
        }
    }

    public void Dispose()
    {
        pollingCancellationToken?.Cancel();
    }
}
```
See the `PollForUpdates()` is called once the parameter is set. I am with you on observing the order status instead, but I don't have a way to bind in a `strong` tag.

**Comment by yopez83** [comment]
Any ideas @EdCharbeneau? I have read your blog about State Management, but still can't get this to work.

**Comment by ADefWebserver** [comment]
@yopez83 The sample expects you to go to the page, then wait for order updates to be streamed. However, the sample only simulates data. See: https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/03-show-order-status.md#see-it-update-in-realtime

**Comment by yopez83** [comment]
@ADefWebserver it's true data is simulated. However, I'd have hoped I could trigger `MyOrder` component to refresh from the `OrderDetails` component once updated. Does it make sense?

**Comment by ADefWebserver** [comment]
> I'd have hoped I could trigger `MyOrder` component to refresh from the `OrderDetails` component once updated. Does it make sense?

Yes, but I would not recommend this approach for what you want. 
At least we know _why_ it wasn't working for you.

**Comment by SteveSandersonMS** [comment]
Sounds like this question is answered.
