### ISSUE TITLE
02-customize-a-pizza missing using directive when using VS Code

### ISSUE THREAD

**Issue by DanJ210** [dotnet-presentations/blazor-workshop#181]
I'm using Visual Studio Code and in the second preview document we are told to add the code for showing the dialog window `<ConfigurePizzaDialog>` but there's an error or tokenization issue that says this is an unexpected name and if it's intended to be a component then add a @using directive for its namespace. Not sure what the namespace should be which is why I'm using this to learn Blazor.

![image](https://user-images.githubusercontent.com/16159685/71552299-57b68980-29c8-11ea-8c5b-0ffa8d7fcc42.png)

**Comment by danroth27** [comment]
Hi @DanJ210. The Blazor support is VS Code is still a work in progress, but has improved quite a bit over the past few months. If you're still seeing this issue with the latest VS Code C# extension, please file an issue in the https://github.com/dotnet/aspnetcore/issues repo and we'll take a look.
