### ISSUE TITLE
Hidden bug for the 'Order' button

### ISSUE THREAD

**Issue by boukenka** [dotnet-presentations/blazor-workshop#185]
Hello,

There is this line of code in index.razor:

```
<a href="checkout" class="btn btn-warning" disabled="@(Order.Pizzas.Count == 0)">
```

It does not work (even there is no display to check it) when there is no ordered pizza.
I replaced it with the following line of code :

```
<a href="checkout" class="@ButtonCssClass">
...
@code
{
private string ButtonCssClass => 
OrderState.Order.Pizzas.Count == 0 ? "btn btn-warning disabled" : "btn btn-warning";
...
}
```

**Comment by yopez83** [comment]
I had no problem with the line mentioned above. I would like to understand more what the situation is, since the button is intentionally disabled when there are no pizzas ordered.

**Comment by boukenka** [comment]
> 
Thank you for your reply.
> 
> The problem is not even that line. It's the condition to either show or hide the parent div. That condition is based on having an Order with Pizzas. Meaning, when you do have, then the parent div will show up and the `disabled` code -though it'll run- will display no difference. We'll never see the disabled effect.

Exactly. This is what I meant with the title 'Hidden bug'. This issue will not be detected because of his parent. Sorry if I was not clear. 

Will it be fixed?

**Comment by yopez83** [comment]
I'd say it will

**Comment by yopez83** [comment]
@boukenka I have submitted a PR with some fixes including the one we discussed here.

**Comment by boukenka** [comment]
Thank you @yopez83 😄 
I am closing this issue if this is Ok.
