### ISSUE TITLE
Upgrade to 3.1.x

### ISSUE THREAD

**Issue by boukenka** [dotnet-presentations/blazor-workshop#186]
Hello,

3.1.1 is due by January 14, 2020 and 3.1 is out since the beginning of December.
Could you plan to upgrade this blazor-workshop to a 3.1.x version with .NET Standard 2.1 please.

**Comment by SteveSandersonMS** [comment]
It was upgraded this week.

**Comment by boukenka** [comment]
Thank you @SteveSandersonMS and @ardacetinkaya
