### ISSUE TITLE
`OrderDetail` Page always re-initialized 

### ISSUE THREAD

**Issue by joonhwan** [dotnet-presentations/blazor-workshop#187]
I'm following this workshop with net core 3.1. 

from [session 3 doc](https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/03-show-order-status.md#polling-for-order-details)

> This uses OnParametersSet instead of OnInitialized or OnInitializedAsync. OnParametersSet is another component lifecycle method, and it fires when the component is first instantiated and any time its parameters change value. If the user clicks a link directly from myorders/2 to myorders/3, the framework will retain the OrderDetails instance and simply update its OrderId parameter in place.
> As it happens, we haven't provided any links from one "my orders" screen to another, so the scenario never occurs in this application, but it's still the right lifecycle method to use in case we change the navigation rules in the future.

but, when I switch between pages as follows 

- `myorders/1`
- `myorders/2`
- `...`

via inputing url in  browser,  it seems that `OrderDetails` component will always re-initialized. 

Is this doc outdated or do i something wrong?

**Comment by yopez83** [comment]
I'm not 100% sure, but I believe when you manually change the url and press <kbd>Enter</kbd>, is the same thing as resubmitting the page. Thus, the component gets reinitialized. If you want to have the SPA like navigation, you should use the `NavigationManager` which is what's intended for.

**Comment by rynowak** [comment]
@yopez83 has the right idea here. Internal navigation driven by the app will behave differently from navigating by pressing enter in the address bar.
