### ISSUE TITLE
Where is GetJsonAsync getting the data from?

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#192]
Where is this method getting the data from?

specials = await HttpClient.GetJsonAsync<List<PizzaSpecial>>("specials");

**Comment by yopez83** [comment]
Is this still an issue?

**Comment by Ricardoaraujo00** [comment]
It is very complicated. I understand that this has nothing to do with Blazor, but would be nice to have a brief explanation or a link for us to go to and learn a bit more about it. 
As i can tell, the server in the program class creates an object of db type, passing to it's constructor a class, and then checks is that db exists, and if no it creates it. It's not clear on how this is verified because it is not passed any path, and the method EnsureCreated() doesn't seems to accept any path. And also, seems a bit weird to me that the seed data gets initialized if  the ensure created method is true. Well, i must assume that this method returns a true value in two cases:
- if the database wasn't present it was created and returns true
- if the data base existes it also returns a true because it is there
And it returns a false when the database is not present and cannot be created.
This leads to a question.
How come the database be initalized, in the case she already exists?
I also assume the database is is always created in the case it is missing because the aplication has always write permissions in it's folder.
Also i can see there is a SeedData.cs file (wich is used to initialize) that has all the info to populate the database in the case it is not present, but it is called on the event the database is present ou created, and it populates some variables and then saves them on the database. But, if database existes this will make duplicated values every time the application is restarted, So, there is something that i'm not understanding on that condition.
Going through all this steps, i arrive now to the point of the question, and this part is where i get completely lost. When i press control and click the GetJsonAsync() method, i go to the aspnet core components where there is some other Json async tasks/methods, and none of them accepts a string as an inpute, and neither have in their signature nothing that makes a reference to <List<PizzaSpecial>>("specials").
Ho, wait, this is a method to get Jason, and Json is tipically handled by an api, wich sits behind an http address, so the string "specials" is an url. It is not clear at first because the application has some configuration on wich it has a base "/" for all adresses it reads, so the "specials" is indeed "/specials". I'm still confused on where that configuration is, and this is related to blazor. Is it because the index page has the first line as so: @page "/"? Or is that configuration somewhere else?
Back to the GetJson. The class SpecialsController has a [Route("specials")] parameter, and also [ApiController] so this is the api that is serving the data as json. It has some kind of dependency injection, wich i struggle to understand how it works also, but i think it is a dependency injection because it looks like an initialization of the controller(don't know if it happens every time it is called). It doesn't receive any pizza context variable, but even so it assing it to a private variable wich in turn is used to return a list of items ordered by descending price.
Well, seems i got to the point trying to explain my difficulties. But many other questions arose along the way, being the most prominent the EnsureCreated() method and how come the database is initialized when already present, the dependency injection thing, and where is configured the base address "/".
@yopez83 , if you could provide me some answers or hints about theses doubts that would be very apreciated.
Should i close this now?

**Comment by Ricardoaraujo00** [comment]
I found the configuration of the base address in the index.html file in the wwwroot folder(<base href="/" />).
In the body there is a div with a class loading bar, wich is the one we see on application startup. But where the application goes from there. Well, where it goes we know, but how is the Index.razor file called from there?

**Comment by yopez83** [comment]
Those are topics related to Dependency Injection and Entity Framework. For more details about how `EnsureCreated()` works click the [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-3.1).
- Now, as to the `GetJsonAsync` method that's the wrong place to go to. That's is part of the `HttpClient` class from [Microsoft.AspNetCore.Blazor.HttpClient](https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.HttpClient/) package. First `/specials` comes from the base Url (index.html line `<base href="/" />`) + the route ("specials"). If you want to find out what code gets executed by navigating to `/specials`. Take a look at [SpecialsController](https://github.com/dotnet-presentations/blazor-workshop/blob/master/src/BlazingPizza.Server/SpecialsController.cs) class from the Server project. Most importantly, if you want to understand how it gets routed there. You should look at how the Routing works. There is a nice presentation about that [here](https://focus.dotnetconf.net/). You can watch the whole presentation or just jump to Routing 1:42:00 - 2:11:00.

**Comment by Ricardoaraujo00** [comment]
Wow! No way i'm going to skip those. So many good things to learn. And i have much to learn. Thank you very much @yopez83 .
