### ISSUE TITLE
<ConfigurePizzaDialog Pizza="configuringPizza" />

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#193]
error description -> Found markup element it unexpected name "ConfigurePizzaDialog". If this is intended to be a component, add a @using directive for its namespace.

This is at session 2 -> Implement the pizza customization dialog
Followed the instructions creating the component but seems visual basic doesn't find him.

Even so it works....

**Comment by yopez83** [comment]
I have followed same steps as in the tutorial and I didn't get this error.

**Comment by kiwiingenuity** [comment]
This is a Visual Studio error.
Use Visual Studio 2019 Preview and the problem will go away.

**Comment by Ricardoaraujo00** [comment]
Thank you for your answers. The error is gone today with no explanation... I'm already using the vs2019 so i think it is better than the preview right?
I' closing this one and will open another because i cannot use, for example, the solution on step2 out of the main folfer. I get a bunch of error. And also that one!!

**Comment by Ricardoaraujo00** [comment]
Seems csharpfritz  already presented the solution to that problem on an issue. Just have to copy the Directory.Build.props file to the solution folder.
