### ISSUE TITLE
Line of code can be removed at "03-show-order-status.md" ending (just by pure preciosity)

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#194]
In the prevoius code we had:
```
async Task PlaceOrder()
    {
        await HttpClient.PostJsonAsync("orders", order);
        order = new Order();
    }
```
And after that was changed to send the user to OrderDetails like this
```
async Task PlaceOrder()
{
    var newOrderId = await HttpClient.PostJsonAsync<int>("orders", order);
    order = new Order();

    NavigationManager.NavigateTo($"myorders/{newOrderId}");
}

```
Since we navigate to another page, when returning to the index page, the order variable is always reseted on page load when it is created with "Order order = new Order();".
Right? Or wrong?

**Comment by yopez83** [comment]
After you post the new order, see next line is `order = new Order();`. Here's where resetting the Order's state happens.
