### ISSUE TITLE
Several changes needed to be done in 04-refactor-state-management.md

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#195]
These needed changes are specifficaly at the "Updating Index" area.
At the text "Now let's move some of the methods from the Index to OrderState", it should be stated that it's not only is needed to copy the functions. They also must be made public on the OrderState class. It is visible on the code provided, but for those who copy they can miss that.
Then, it's not said anywhere, but on the index.razor we also must change many other things. First of all, to access those functions on the new class we must precede all methods with the class name, like
 
`<li @onclick="@(() => OrderState.ShowConfigurePizzaDialog(special))" ....`

And all variables "order" must be replaced with "OrderState.Order". Some lower casing to upper casing changing must be done in some function calling in index.razor because they seem to differ from the code now provided to copy from in this page.

With this changes the application can be compiled and runs ok.

**Comment by yopez83** [comment]
I see your point here, but although the tutorial doesn't say the audience should have some basic C# background, it is assumed.
