### ISSUE TITLE
Issue in 06-authentication-and-authorization.md at "Tracking authentication state"

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#197]
When it says "... then register this as a DI service in Startup.cs:"
Should also be said we need to reference the Authorization "thing" at the top. Don't know how that should be named.

`using Microsoft.AspNetCore.Components.Authorization;`

**Comment by yopez83** [comment]
The word you're looking for is directive. As to whether should be mentioned or not, I see your point. However, since VS 2019 is smart enough to let you know you're missing a directive, and gives you a way to add it right away (Ctrl + .), I guess that's the reason why it was omitted.
