### ISSUE TITLE
Error parsing a meta element's content - 06-authentication-and-authorization

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#198]
Following the section "Ensuring authentication before placing an order"
I get these errors shown on console very briefly and i have already completed the tutorial.

> Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.

At:

> authenticate:8

And a error with an x in a red circle:

> Refused to load the image 'https//api.twitter.com/favicon.ico' necause it violates the following Content Security Policy directive: "img-src https//abs.twimg.com https//*.twimg.com https://pbs.twimg.com data".

> At authenticate:1

 
It hapens when the line of code "NavigationManager.Navi..." runs
```
@code {
    [CascadingParameter] Task<AuthenticationState> AuthenticationStateTask { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateTask;
        if (!authState.User.Identity.IsAuthenticated)
        {
            // The server won't accept orders from unauthenticated users, so avoid
            // an error by making them log in at this point
            NavigationManager.NavigateTo("user/signin?redirectUri=/checkout", true);
        }
    }

    // Leave PlaceOrder unchanged here
}
```
If i coment the "NavigationManager.Navi..." line the error doesn't show in console, so must be something in that line but i don't know what. The user controller class runs on the server so if there is some error there it shouldn't show up that way in the browser console.

Maybe it is something to do with this code inside the user controller at "/user/signin" route:
```
await HttpContext.ChallengeAsync(
                TwitterDefaults.AuthenticationScheme,
                new AuthenticationProperties { RedirectUri = redirectUri });
```
This has nothing to do with Blazor, it's about aspnet core authorization, but even so, it's in the demo, so... maybe worth to fix. Or maybe it's not a big deal because the application works.

**Comment by rynowak** [comment]
When you authenticate you get redirected to **twitter's** authentication page and then back to your website. I'm pretty sure these browser errors are coming from twitter (as evidenced by the URLs you shared).
