### ISSUE TITLE
Why not implement the backend for received orders?

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet-presentations/blazor-workshop#201]
Hi
I'm suggesting this because there is no example on how to the UI updates upon received data from else where than the own page. The sigleton aproach exemplified here injects and instantiates a class in the page, but we cannot access it from anywhere else on the program. If i have a page displaying the orders arriving, this aproach seems that cannot be used. 
How can i create a object for whom are passed the orders that are received, and those orders appear in the UI as soon as they arrive like a bind, without any second by second check? Right now i can't even do it with a string...

With the example provided we cannot access the orders class from other task that we could have running. The only way that this can be partially accomplished is by creating a thread safe singleton, but not inject it on IConfigureServices or an error will be thrown that it has not a vallid constructor. 
```
public class ThreadSafeSingletonString
    {
        private static ThreadSafeSingletonString _instance;
        private static readonly object _padlock = new object();
        private ThreadSafeSingletonString() 
        {
  
        }

        public static ThreadSafeSingletonString Instance
        {
            get
            {
                if (_instance == null)
                {
                    lock(_padlock)
                    {
                        if (_instance == null)
                        {
                            _instance = new ThreadSafeSingletonString();
                            _instance.order="";
                        }
                    }
                    
                }
                return _instance;
            }
            set
            {
                _instance.order = value.order;
                _instance.NotifyDataChanged();
            }
        }
        public string order { get; set; }

        public event Action OnChange;

        private void NotifyDataChanged() => OnChange?.Invoke();
    }
}
```
It must be instantiated on the Program.Main 
```
  public static void Main(string[] args)
        {
            var tss = ThreadSafeSingletonString.Instance;
            tss.order = "nome";
            Console.WriteLine(tss.order);
            CreateHostBuilder(args).Build().Run();
        }
```
and then use it on the Blazor page, by referencing or injecting. Right now i don't remember wich one i used. This way i can access a variable on all the program scope. But seems that the bind doesn't works properly because the page only refreshes after navigate to another page and come back.

I'm also trying with a static class
```
public static class InstanceTransporterClass
    {
        static string _order;
        public static string order {
            get =>_order
            {
                _order = value;
                NotifyDataChanged();
            }
        }

        public static event Action OnChange;

        private static void NotifyDataChanged() => OnChange?.Invoke();
    }
```
This way the value can also be accesible on the page and on the backend method. But like the singleton aproach the page doesn't automatically render the UI. I tried to use the action method that i copied on the sigleton example but it throws an error 
```
`fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'FullUpdateToBalcony'.
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
   at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at BlazorApp1.Data.InstanceTransporterClass.NotifyDataChanged() in D:\TestFolder\BlazorApp1\Data\InstanceTransporterClass.cs:line 22
   at BlazorApp1.Data.InstanceTransporterClass.set_queue(String value) in D:\TestFolder\BlazorApp1\Data\InstanceTransporterClass.cs:line 16
   at GrpcService1.GreeterService.FullUpdateToBalcony(BalconyFullUpdate request, ServerCallContext context) in D:\TestFolder\BlazorApp1\Data\GreeterService.cs:line 123
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)`
```

I don't know if i received this error on console while using the singleton but the page didn't updated either...
In the Blazor page i have:
(The InstanceTransporterClass is named this way because i was trying to use it before to pass the pointer of the instantiated in the UI to the backend...)
```
@page "/greeter"
@inject GrpcService1.GreeterService GreeterService1

@inject AppData appdata1



@using BlazorApp1.Data

<h1>Grpc Connection</h1>

<input type="text" @bind="@Name" />
<button @onclick="@SayHello">SayHello</button>
<p>Fila recebida</p>
<input type="number" @bind="appdata1.datahoje" />
<input type="text" @bind="appdata1.datahoje" />
<p>@Greetmsg</p>
                                                                                                         
<p>TransporterClass data: @InstanceTransporterClass.order</p>

@code {
    string Name;
    string Greetmsg;
    //ThreadSafeSingletonString threadSafeSingleton = ThreadSafeSingletonString.Instance;

    //protected override void OnInitialized()
    //{
    //    threadSafeSingleton.OnChange += StateHasChanged;
    //    appdata1.OnChange += StateHasChanged;                                                                                                                                                                             
    //}

    protected override void OnInitialized()
    {
        InstanceTransporterClass.OnChange += StateHasChanged;
    }

    public void Dispose()
    {
        InstanceTransporterClass.OnChange -= StateHasChanged;
    }

    async Task SayHello()
    {
        this.Greetmsg = await this.GreeterService1.SayHello(this.Name);
    }

}

```

**Comment by rynowak** [comment]
This is a pretty long post, and I'm not 100% sure what you're after here.

The pattern that you outlined here seems pretty reasonable, and will work. I'd suggest using a singleton service in DI rather than a static as that would be more testable.

**Comment by Ricardoaraujo00** [comment]
Hi @rynowak  
I cannot inject thread safe singleton being in the ConfigureServices on the startup.cs because the compiler says is has not a valid constructor. The solution that i came up with, instantiating the singleton in the program.main(), will not give me a session independent variable as supposedly does the addscooped singleton injection method in the ConfigureServices at startup.cs. I would have to separate the data manually for the different users...
Ho, think i was doing a big mess in by head....
I was trying to understand one thing in another use case scenario. I was thinking of this like what macdonalds does in their stores, because they have those terminals that are running like a website, very much like this website, and clients can make the orders there. In this case scenario, in the pizza backend should exist a terminal, let's say the main server, receiving the orders that are made inside the store. And in the kithchen there must be at least one terminal for the employees to see what needs to prepared and for whom. And as soon as orders arrive in the kitchen from the main server, they would be shown in the screen on a Blazor page also.
I think there are two possibilities from here. Those kitchen terminals pull the data trough an API called from code within the page code, or they receive it asynchronously by gRPC. If it's by an API, as soon as each response arrives the binded variable changes, and the UI is updated, because the page is closely linked to that action as the update method is running in the page code. But if the preparation orders are received assyncronously for example by gRPC, there is not that connection to the page because the method that receives the information is on another completely separated service within the same running application. Of course, in this situation there is no way to update automatically the page contrary to my initial thought, because the page is being handed to a http client(browser) and really it makes no point to what i was thinking on accessing the page variable. And now is clear on why is not possible to access the scooped class from anywhere else in the code. That instance is on another completely different part of the application(in http service) and of course is not accessible else where from that domain.

So, to come to an end... I was just very confused. And if i want to have that terminal in the kitchen that receives the orders, i have to receive them from a method running in the page and pooling the server constantly to check if there are any new orders. Or in the case i use a gRPC service, the method in the page does only pooling to the own application global variable(singleton) that has that data. This last method seems preferable because it would generate less traffic in the network and the pooling for new data would be faster and easier i think.

Sorry for this rookie inexperience of mine.
Maybe i even said some more things that are wrong, and you have the time and the will to correct me i would be very appreciated.
Thank you for your initial reply.

**Comment by Ricardoaraujo00** [comment]
I have one more doubt

Shouldn't i be able to subscribe to a sigleton change event from a Blazor page, and if it occurs get some function int he page to be executed? Like this:

```
public string  fromService ;
protected override void OnInitialized()
  {
        threadSafeSingleton.OnChange += UpdateOrder();
    }

    public System.Action UpdateOrder()
    {
        this.fromService = threadSafeSingleton.onumber;
        Console.WriteLine("Passed by UpdateOrder");
        this.StateHasChanged();
        return StateHasChanged;
    }
```

**Comment by yopez83** [comment]
@Ricardoaraujo00 this issue was already closed. Let's do one thing to see if I can help. Can you open a new issue and say what you want to achieve? I know you're trying to avoid the long polling for UI updates.

**Comment by Ricardoaraujo00** [comment]
Sorry @yopez83 i didin't ment to open it. Was just explaining my thought and also trying, in this same issue, to get more info about the Blazor bind possibilites for this case scenario where information comes from outside with no user interference. If there if no efficient way(not a every second check) of detecting that some variable changed in the Blazor server, maybe the proper implementation would really be the long pooling directly from the Blazor page to the pizza store main server. But this is a client Blazor app, not a server hosted. I assume that in this Blazor worksop application i cannot use gRPC directly from de code in the page as i can do in an hosted one. So the only long polling usable with this workshop app is an long polling HTTP request to an API. 
Yes, i'm trying to avoid long pooling because seems harder to pause an API ou gRPc funtion and get it resumed when a new order arrives to the main server.
Ok, i'll open one issue for the first use case scenario.
Thanks
