### ISSUE TITLE
Ca'nt run any example

### ISSUE THREAD

**Issue by ricardochimenes** [dotnet-presentations/blazor-workshop#212]
Hey guys, i'm having a hard time trying to run any of the examples. Right now, my pizza app never loads, it keeps running in the loading bar step, no matter which project I run. I've already update and checked everything I think it could be. Any thoughts on that? Thanks

**Comment by justSteve** [comment]
I'd suggest stepping into the Package Manager Console to see if any packages need added/updated. Right click the solution node (top level of Solution Explorer) and 'Clean Solution' then 'Rebuild Solution'. Are you getting any error messages?

**Comment by ricardochimenes** [comment]
I already tried that, no lucky. 

i'm getting an error "ILLink failed with exited code 1". Not sure what is causing this, since other people seems to had not bumped into this. If I try to run it anyway, i got stuck in a loading page

**Comment by jongalloway** [comment]
@ricardochimenes Try this workaround for the "ILLink failed with exited code 1" error: https://github.com/dotnet/aspnetcore/issues/17754

**Comment by ricardochimenes** [comment]
> @ricardochimenes Try this workaround for the "ILLink failed with exited code 1" error: [dotnet/aspnetcore#17754](https://github.com/dotnet/aspnetcore/issues/17754)

That worked, the issue was the user name folder. Thank you so much!
