### ISSUE TITLE
Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server please set an example with roles

### ISSUE THREAD

**Issue by carlosalcantara2668** [dotnet-presentations/blazor-workshop#215]
Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server please set an example with role

**Comment by danroth27** [comment]
Hi @carlosalcantara2668. We do plan to update the workshop to use IdentityServer for authentication. The Blazor WebAssembly templates now support authentication with IdentityServer out of the box: https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/hosted-with-identity-server. We are tracking adding an example that shows how to use IdentityServer with roles with https://github.com/dotnet/aspnetcore/issues/19769. Closing this issue as a duplicate.
