### ISSUE TITLE
Adding Authorize attribute does not generate an HTTP 302

### ISSUE THREAD

**Issue by tomvdhole** [dotnet-presentations/blazor-workshop#229]
When adding the Authorize attribute onto the OrdersController, i receive a 401 httpstatus code instead of a 302 httpstatus code
thx for any help

**Comment by destects** [comment]
I second this, even picking up from checkpoint 5, and making the first change, (uncommenting [Authorize] and adding the using statement.), I get the 401 status code. with an unhandled error

**Comment by tomvdhole** [comment]
i think we have to add to the razor file an @attribute [Authorize] tag and then we get the right code, now we get the 401 from the API, that's ok, you don't want a 302 when you just directly call the webapi. But when you call from a page, just like we try to do we want the 302.
Unfortunately i cannot check for the moment because my private pc is broken

**Comment by tomvdhole** [comment]
OK i just had some spare time, i have tried it, you must set the @authorize attribute and also in your code that will do the actual action (for me it is now in Checkout.razor method: PlaceOrder)
you must request your accestoken, if you get a token, you can do the rest that you want, otherwise you will be redirected to the "tokenResult.RedirectUrl

**Comment by tomvdhole** [comment]
also @authorize attribute only works when in App.razor you have set the Routeview to AuthorizeRouteView

**Comment by tomvdhole** [comment]
The StatusCode 302 comes from the IdentityServer not from the webapi.
When you try to connect to the webapi (with the Authorize attribute on the webapi) you get the 401 (that's what you want)
To get it work you have to add an authorize attribute to the razor file.
You should also create the Authentication page, the authorize attribute will call this page.
This page will call the RemoteAuthenticatorViewCore that will call the identityserver
When you are not logged in that will generate the 302 statuscode with the link to the page on the identityserver to login

also @authorize attribute only works when in App.razor you have set the Routeview to AuthorizeRouteView
