### ISSUE TITLE
Components and Layouts - Error in documentation

### ISSUE THREAD

**Issue by chriswpowell** [dotnet-presentations/blazor-workshop#232]
Where you add this code.

```
@code {
    List<PizzaSpecial> specials;

    protected override async Task OnInitializedAsync()
    {
        specials = await HttpClient.GetFromJsonAsync<List<PizzaSpecial>>("specials");
    }
}
```
 ```HttpClient.GetFromJsonAsync``` should be ```HttpClient.GetJsonAsync```

**Comment by yopez83** [comment]
In the `Index.razor` page. And yes, you're right about the `GetJsonAsync`

**Comment by lohithgn** [comment]
@chriswpowell @yopez83 

BlazingPizza.Client project references `System.Net.Http.Json` version 3.2.0. This library contains HttpClientJsonExtensions helper class. This helper class doesn't have GetJsonAsync() method. It has GetFromJsonAsync() - which will retrieve the json content from server and deserialize the content to provided type and return the deserialized type back to caller. Here is the HttpClientJsonExtensions docs: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions?view=net-5.0&viewFallbackFrom=netcore-3.1

So in my view - the code is correctly written.

If you think that this is no longer an issue, do consider closing the issue.

**Comment by lohithgn** [comment]
@chriswpowell If this is no longer an issue for you, do consider closing this issue. Thanks.
