### ISSUE TITLE
Error from: builder.Services.AddRemoteAuthentication<PizzaAuthenticationState, ApiAuthorizationProviderOptions>();

### ISSUE THREAD

**Issue by PatrickOne1** [dotnet-presentations/blazor-workshop#244]
Hi!
I can't compile due to builder.Services.AddRemoteAuthentication<PizzaAuthenticationState, ApiAuthorizationProviderOptions>(); gives a:
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddRemoteAuthentication' and no accessible extension method 'AddRemoteAuthentication' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by danroth27** [comment]
I believe you are either missing a using directive for `Microsoft.Extensions.DependencyInjection` or you don't have package reference for Microsoft.AspNetCore.Components.WebAssembly.Authentication that successfully restored.

**Comment by PatrickOne1** [comment]
Since you mentioned Microsoft.AspNetCore.Components.WebAssembly.Authentication I tried different  versions and up to preview 3 it works, but after that you get the previously mentioned error.
