### ISSUE TITLE
HttpClient instances that include access tokens

### ISSUE THREAD

**Issue by ToiWright** [dotnet-presentations/blazor-workshop#252]
In the Visual Studio Blazor WebAssembly App the template includes the following code in the **Program.cs** file.

```
// Supply HttpClient instances that include access tokens when making requests to the server project
builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp3.ServerAPI"));

```
Is it your intention to do the same thing in the tutorial?

**Comment by danroth27** [comment]
Hi @ToiWright. I was planning to update the workshop this weekend to use strongly typed clients with an HttpClient that has been preconfigued with the new `BaseAddressAuthorizationgMessageHandler`.
