### ISSUE TITLE
"The RunCommand" property is not defined

### ISSUE THREAD

**Issue by jwu-dharmo** [dotnet-presentations/blazor-workshop#266]
A Blazor newbie here.

I downloaded the projects and updated all the packages.  The solution compiled, but when I tried to run it, I got a pop-up:

_Unable to run your project.  The "RunCommand" property is not defined._

I checked the project type for both the client and the server, and both are set to "Console Application".  Scratching my head.

**Comment by danroth27** [comment]
@jwu-dharmo Things should be updated to the latest Blazor WebAssembly release now and all projects should build and run. Let us know though if you're still seeing issues!
