### ISSUE TITLE
Refactor state management showing wrong set BaseAddress code

### ISSUE THREAD

**Issue by blfuentes** [dotnet-presentations/blazor-workshop#278]
In the docs 
https://github.com/csharpfritz/blazor-workshop/blob/master/docs/04-refactor-state-management.md

The code used for setting the BaseAddress seems to be wrong.
`builder.Services.AddBaseAddressHttpClient();`

Should be 
` builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) }); ` as it can be seen in the source code.

**Comment by lohithgn** [comment]
@blfuentes the doc has been updated. You can take a look at the 04 section doc again.

Consider closing this issue if you think doc has been corrected. Thanks. 👍

**Comment by blfuentes** [comment]
Doc was updated
