### ISSUE TITLE
Amazing blazing pizza's

### ISSUE THREAD

**Issue by DimitriVanhaecke** [dotnet-presentations/blazor-workshop#297]
Thank you for the great workshop guys,  

Keep it up !

**Comment by Christian-Oleson** [comment]
> Thank you for the great workshop guys,  
> 
> 
> 
> Keep it up ! 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

@DimitriVanhaecke ,
Since this is not an issue, can you close this?
