### ISSUE TITLE
Any reason to have the Client and Server projects? 

### ISSUE THREAD

**Issue by raulandresduque** [dotnet-presentations/blazor-workshop#301]
Hello,

More than an issue, it is a doubt (I didn't find another point to comment on) ...

About the need of having two projects, one for the server (MVC) and the other one client (Blazor).

Any technical reason / best practice for it instead of having only one blazor project?

**Comment by devjinjin** [comment]
It is practice project.
The project you saw is no longer in use.

My other git project path is below :
https://github.com/codingzombie82/Service

Use dotnet core api + blazor client.

2021년 2월 5일 (금) 오후 12:28, Raul Duque <notifications@github.com>님이 작성:

**Comment by devjinjin** [comment]
It is practice project.
The project you saw is no longer in use.

My other git project path is below :
  https://github.com/codingzombie82/AppService

Use dotnet core api + blazor client.

2021년 2월 5일 (금) 오후 2:14, 이진영 <devjinjin@gmail.com>님이 작성:

**Comment by lohithgn** [comment]
@raulandresduque If i understand your question correctly - You are asking about BlazingPizza.Server & BlazingPizza.Client. Blazor WebAssembly has 2 hosting models:

- Host it as a static web site in a web server 
- Use ASP.NET as a server which hosts the Blazor WebAssembly app and serves it to the browser

In this workshop the second model is showcased. Plus the BlazingPizza.Server is also used to house the APIs powering the Blazor WebAssembly application (lile pizza api endpoint, order end point, toppings endpoint etc).

This is a typical practice followed by most people.

Hope this helps.

**Comment by lohithgn** [comment]
@raulandresduque if you think your questions is answered - please consider closing this issue. Thanks.
