### ISSUE TITLE
Question about the Pound

### ISSUE THREAD

**Issue by ChristopherPS96** [dotnet-presentations/blazor-workshop#307]
Hello, hopefully somebody can help me with this.
I want to change the pound-sign to euro, but I can't find where to do it. 
I thought it would just be added somewhere, but the only occurrence was in site.css, where it didnt matter if I changed  £ to €.

Please tell me I'm just blind.

**Comment by ylr-research** [comment]
Few places, do `ctrl` + `shift` + `F` to search, then select **Entire Solution** and enter the `£`

**Comment by ChristopherPS96** [comment]
![image](https://user-images.githubusercontent.com/39082942/113581771-df596200-9627-11eb-9f4e-528d57acf9b3.png)
After some searching the only places I could achieve a difference was with the size price and topping price (because there I found the £ sign, directly through searching like you suggested with ctrl + shift + F). But Visual Studio doesn't find anything else anymore.

**Comment by ylr-research** [comment]
`MyOrders.razor`, `ConfigurePizzaDialog.razor`, `OrderReview.razor` and `site.css`. That should be it

**Comment by ylr-research** [comment]
I'd suggest you try Globalization and Location for a more dynamic approach. Check this [doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#:~:text=Blazor%20Server%20apps%20are%20localized%20using%20Localization%20Middleware.,examples%2C%20see%20Globalization%20and%20localization%20in%20ASP.NET%20Core.)

**Comment by ChristopherPS96** [comment]
Okay I checked those files again, but didn't found any pound-signs left. I'm getting mad here.
[Pages.zip](https://github.com/dotnet-presentations/blazor-workshop/files/6260178/Pages.zip)

Thanks for the tip with the more dynamic approach. But first I need to be able to change the currency sign before thinking about that.

**Comment by ylr-research** [comment]
Aside those pages, what other page or component you see it in?

**Comment by jongalloway** [comment]
Make sure you get all 4 in [site.css](https://github.com/dotnet-presentations/blazor-workshop/blob/49aa7247498308f7c78ca1c84cc6135dd0b8ec81/src/BlazingPizza.Client/wwwroot/css/site.css#L202) - https://github.com/dotnet-presentations/blazor-workshop/blob/49aa7247498308f7c78ca1c84cc6135dd0b8ec81/src/BlazingPizza.Client/wwwroot/css/site.css#L202 (lines 202,254,311,458)

Not sure if browser could be caching, but doesn't hurt to ctrl-f5 to hard refresh.
