### ISSUE TITLE
Project only runs from VS2019

### ISSUE THREAD

**Issue by AmSmart** [dotnet-presentations/blazor-workshop#309]
Whenever I startup this project from VS2019, it runs smoothly. Running it from the CLI with ``dotnet run`` always leads to a runtime exception on start-up. What could be wrong?

**Comment by ylr-research** [comment]
I'd very helpful to add some context, like a snapshot of the error. Also details such as VS edition you're using, have you upgraded any package?

**Comment by AmSmart** [comment]
I didn't upgrade any of the packages. I just downloaded and ran a fresh copy from the repo. Just tried it again this morning and all works perfectly. I guess it has to do with some weird issue. I'm going to close this GitHub issue right now since the problem most likely didn't originate from the repo. Thanks for the swift response.
