### ISSUE TITLE
Add session screen shots

### ISSUE THREAD

**Issue by danroth27** [dotnet-presentations/blazor-workshop#31]

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/51807619-f4d0e580-2280-11e9-9891-2a9cd7b2a49b.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/51807831-dfa98600-2283-11e9-9e66-2a7f52a2e7f8.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/51807869-5f375500-2284-11e9-8417-dcd572cd028d.png)

**Comment by danroth27** [comment]
![image](https://user-images.githubusercontent.com/1874516/51843485-06f76600-230b-11e9-91e6-517f6d78f13c.png)

**Comment by danroth27** [comment]
![Publish from VS](https://user-images.githubusercontent.com/1874516/51885818-2501ac80-2385-11e9-8025-4d1477083a8d.png)

**Comment by danroth27** [comment]
![image](https://user-images.githubusercontent.com/1874516/51885912-7f027200-2385-11e9-8707-0e2f82b543fd.png)

**Comment by danroth27** [comment]
![image](https://user-images.githubusercontent.com/1874516/51886491-fc2ee680-2387-11e9-9c16-5f1fc47365fa.png)

**Comment by danroth27** [comment]
![image](https://user-images.githubusercontent.com/1874516/51886593-5a5bc980-2388-11e9-9329-7e015901e45d.png)

**Comment by danroth27** [comment]
![image](https://user-images.githubusercontent.com/1874516/51886932-a52a1100-2389-11e9-8b58-6ea3ae5a4291.png)

**Comment by rynowak** [comment]
Closing because these are already referenced in the workshop. Leaving the issue open doesn't do anything 😆

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59218134-674ebc00-8bb7-11e9-97d6-0c9985f10acf.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59219467-76833900-8bba-11e9-960b-67aec2e2f8c7.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59220316-93207080-8bbc-11e9-8bbb-f3f5ec8a29d6.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59221577-85201f00-8bbf-11e9-9de6-f24f93a6a483.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59221927-4b034d00-8bc0-11e9-96ef-6c41ad727cb7.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59222864-6a9b7500-8bc2-11e9-9f90-ae1d47fc23d7.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59272849-cb708f00-8c4e-11e9-9201-d350fb7ec9f9.png)

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59276053-78e6a100-8c55-11e9-91ee-0abd8dfad069.png)

**Comment by rynowak** [comment]
FWIW - pasting an image into github doesn't require you to actually open an issue or submit the comment. You can just click on `New Issue`, and paste in your image, and then close the browser tab.

**Comment by SteveSandersonMS** [comment]
I was concerned that they might purge images that aren't referenced from anywhere. Maybe that's unlikely!

**Comment by danroth27** [comment]
I just like having a single place with all the images for the changes I'm working on in case I want to reference them at a later date.

**Comment by rynowak** [comment]
http://lmgtfy.com/?q=Create+a+github+repo
