### ISSUE TITLE
unable to debug blazor client code in this project

### ISSUE THREAD

**Issue by bebo-dot-dev** [dotnet-presentations/blazor-workshop#315]
Hi guys, 

I'm running with:
* Linux Mint v20.2 
* Visual Studio Code v1.58 (June 2021) 
* DotNetCore v5.0.205
* C# for Visual Studio Code v1.23.13
* Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.1.0

At a basic level I'm trying to get started with /00-get-started and before proceeding on, I'd like to be sure that things are configured correctly including being able to debug both blazor code and server code. 

This problem I have appears to be localised to this project and I expect it is somehow configuration related. The reason I say this is that I am able to create a basic fresh new blazor application with `dotnet new blazorserver` and I am able to debug this simple blazor client code with my setup.

I've zipped up and attached a few config files related to this project that are probably related to getting this working, if someone has a similar setup to mine, I appreciate any help.

[.vscode.zip](https://github.com/dotnet-presentations/blazor-workshop/files/6860523/default.vscode.zip)
[launchSettings.json.zip](https://github.com/dotnet-presentations/blazor-workshop/files/6860527/launchSettings.json.zip)

Thanks Joe

**Comment by lohithgn** [comment]
@bebo-dot-dev 
The Blazing Pizza Workshop code is built on Blazor Server technology stack.

I took a look at your launch.json. Here is what you have:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/BlazingPizza.Server"
        }
    ]
}
```
Notice that you are setting the Server project as blazorwasm type.

I did a new blazor server project using the command: `dotnet new blazorserver`. Here is the launch.json that got generated when i said Run&Debug in VSCode:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/net6.0/blazor-server.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

You are trying to debug a Blazor Server project as a Blazor Web Assembly project. 

Note: I tested this with .NET 6 SDK.

Hope this helps.
