### ISSUE TITLE
Move project to .NET 6

### ISSUE THREAD

**Issue by timheuer** [dotnet-presentations/blazor-workshop#320]
Migrate project to .NET 6 / C# 10:

- [x] Update project TFMs to `net6.0`
- [x] Move to implicit usings
- [x] Move to minimal hosting APIs for web
- [x] Move to file-scoped namespace / top-level programs where possible

**Comment by danroth27** [comment]
Fixed by https://github.com/dotnet-presentations/blazor-workshop/pull/330.
