### ISSUE TITLE
order-total div will not display unless I place it above orders

### ISSUE THREAD

**Issue by marqdouj** [dotnet-presentations/blazor-workshop#323]
Hi,
I am using VS2019 and Windows 11 with a display size of 1366x768. 
I am new to html/css so I'm not sure the proper way to fix this. I thought maybe adding a overflow:auto to the divs might work but that seemed to have no effect.
So I move the div above the orders, but then the orders are not scrolled properly (and the pizzas as well).
Please see attached photos.

![BlazingPizza - overflow issue](https://user-images.githubusercontent.com/16510416/137333232-11bb0c03-db02-44b2-886c-30b19251beb4.png)

![BlazingPizza - overflow issue - move to top](https://user-images.githubusercontent.com/16510416/137333257-18236f83-a008-4988-aef0-310eb09b029b.png)

**Comment by Gio2k** [comment]
I am having the same problem. Also, the main content where the pizzas are displayed does not show the scrollbar. Maybe a problem with the css?

**Comment by ajt2018** [comment]
>  Also, the main content where the pizzas are displayed does not show the scrollbar.

Have a look in \BlazingPizza.Client\wwwroot\css\site.css and change the `overflow-y` in `body {...}`

**Comment by ylr-research** [comment]
As of now this is still an issue

**Comment by ylr-research** [comment]
Have you experienced this @csharpfritz?
