### ISSUE TITLE
can you provide a RC/server-side version of this?

### ISSUE THREAD

**Issue by agonzalezm** [dotnet-presentations/blazor-workshop#48]
Would be great to see a RC/server-side version of the  blazzing pizza application and workshop with best practices on authentication, identity, validations, etc

**Comment by indcoder** [comment]
Agree with this. Other project in the example workshop genre usuallu follow the practice of having different branches...in Blazor case, we would have a separate branch for the client [WASM] and for the server side [SignalR based] projects. Very crucial for the authentication and authorization aspect.

**Comment by neven10** [comment]
https://github.com/aspnet/Docs/issues/10742

**Comment by rynowak** [comment]
We're updating the workshop as previews come out, and we will continue to do so until the first full Blazor release.
