### ISSUE TITLE
User's display name encoding

### ISSUE THREAD

**Issue by ladeak** [dotnet-presentations/blazor-workshop#52]
```UserController.SignInCompleted``` returns userState in json. But this will not be able to handle accent characters like my name László. I suggest adding some encoding and ```UserStateProvider.OnSignInStateChanged``` method should decode or fire 
```
CurrentUser = await HttpClient.GetJsonAsync<UserState>($"/user");
```

**Comment by rynowak** [comment]
I suspect that what's happening here is actually that the **decoding** is busted. Blazor currently using SimpleJSON which has had lots of random bugs for us. We're switching to use System.Text.Json for preview 6 and I'll try this out then.

**Comment by rynowak** [comment]
This has been fixed. We had issues with our templates creating files with bad encodings
