### ISSUE TITLE
Upgrade to Blazor 0.9.0

### ISSUE THREAD

**Issue by mbowles201** [dotnet-presentations/blazor-workshop#60]
Is this possible?  I have tried numerous pathways and no luck.

**Comment by JeroenvdBurg** [comment]
hi, I have forked and changed the project to work with latest blazor version (0.9). 

you can find the starting point at: https://github.com/JeroenvdBurg/blazor-workshop/tree/blazor-0.9-dotnetcore3-preview2/save-points/00-Starting-point

hope that helps

good luck!

**Comment by mbowles201** [comment]
Great, I will take a gander. Thanks

**Comment by JeroenvdBurg** [comment]
and the update for preview4 is here, a lot of changes: 

https://github.com/JeroenvdBurg/blazor-workshop/tree/blazor-0.9-dotnetcore3-preview4

**Comment by rxelizondo** [comment]
@JeroenvdBurg 

I see that you updated the code under the "00-Starting-point" folder to work with the latest version of Blazor (thanks for that) however there appears to be an issue.

If you open the project and compile it everything works fine, however, if you start working your way through the workshop the application will crash as soon as you add `@inject HttpClient HttpClient` to the index page. The error is:

`InvalidOperationException: Cannot provide a value for property 'HttpClient' on type 'BlazingPizza.Client.Pages.Index'. There is no registered service of type 'System.Net.Http.HttpClient'.`

Thanks.

**Comment by JeroenvdBurg** [comment]
@rxelizondo thanks for the feedback. You are right, because I switched to blazor server side you need to inject the HttpClient manually. I have commited the change.

**Comment by JeroenvdBurg** [comment]
Also recommend looking at the full implementation of @ADefWebserver https://github.com/ADefWebserver/BlazingPizza 

here the server and client project are combined. 

For a full working solution of Blazor Client side (webassembly) see https://github.com/SQL-MisterMagoo/blazor-workshop

**Comment by danroth27** [comment]
We'll skip 0.9.0 and update to Preview 5.
