### ISSUE TITLE
Missing "using" directive for map component in _Imports.razor

### ISSUE THREAD

**Issue by MiKom** [dotnet-presentations/blazor-workshop#64]
Hi,

I'm doing this awesome workshop on "preview5" branch (downgraded to preview4 because preview5 is not yet out) and I couldn't get the map to work.

It turns out that the save point projects for chapters 00-05 are missing using statment for map component in `BlazingPizza.Client\_Imports.razor`:
```
@using BlazingPizza.ComponentsLibrary.Map
```

Either this should be mentioned in chapter about map or it should be added to the `_Imports.razor` file in save point projects.

**Comment by rynowak** [comment]
Thanks for the report. Adding this using is now part of the instructions for section 6.
