### ISSUE TITLE
It should be mentioned that UseAuthentication(); should be used after UseRouting(); 

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet-presentations/blazor-workshop#65]
In https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md

> If the app uses authentication/authorization features such as AuthorizePage or [Authorize], place the call to UseAuthentication and UseAuthorization after UseRouting.

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio

**Comment by rynowak** [comment]
Thanks @wrkettlitz - I can't find the instance you're talking about that's wrong. I did a search for every use of `UseAuthorization()` and everything likes like what I would expect. Please comment or log a new issue if I missed something.
