### ISSUE TITLE
Components not loading

### ISSUE THREAD

**Issue by dylanevs** [dotnet-presentations/blazor-workshop#74]
Completed projected compiled and run components not showing on page errors displayed in debug
![image](https://user-images.githubusercontent.com/19555971/57739329-1a0c2700-76ab-11e9-868a-2e640c6f69f4.png)

**Comment by rynowak** [comment]
Hi @dylanevs sorry that you're having problems. Can you try this again with the latest code? we fixed some issues in the server project past few days.

If you're still have problems then I'll need more information to be able to help, what step are you on? etc.
