### ISSUE TITLE
Where are the workers and the gRPC sample you showed at Build?

### ISSUE THREAD

**Issue by BrightSoul** [dotnet-presentations/blazor-workshop#75]
I searched various branches but I couldn't find it.

**Comment by rynowak** [comment]
@danroth27

**Comment by danroth27** [comment]
The workers and gRPC code is not part of the workshop but is part of a fork I put together here: https://github.com/danroth27/blazingpizza.

I hope this helps!

**Comment by BrightSoul** [comment]
> I hope this helps!
Yes, thank you so much!!
