### ISSUE TITLE
Server application lacks UseBlazorDebugging call

### ISSUE THREAD

**Issue by rysep2** [dotnet-presentations/blazor-workshop#76]
I am trying to debug the application but since it's started from the BlazingPizza.Server Project and not the BlazingPizza.Client Project the debugger does not seem to start.

After entering the keys Shift + Alt + D, a new tab opens with the message:
http://localhost:64589/_framework/debug?url=http%3A%2F%2Flocalhost%3A64589%2F

Running the following command in the run dialog doesn't work either:
"%programfiles(x86)%\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 http://localhost:64589/

What is the right way to debug this application?

**Comment by rynowak** [comment]
@SteveSandersonMS - do we have a set of instructions available for client-side debugging?

**Comment by SteveSandersonMS** [comment]
The instructions are just to do what it says in the console, i.e. press Shift+Alt+D and follow the on-screen instructions.

> Running the following command in the run dialog doesn't work either

Looks like `BlazingPizza.Server` lacks a call to `app.UseBlazorDebugging();` inside the `if (env.IsDevelopment())` block in `Startup.cs`. I'll update this issue title to reflect that, since it's a defect we should fix.

@rysep2 To fix this, add the line `app.UseBlazorDebugging();` directly above or below this line: https://github.com/dotnet-presentations/blazor-workshop/blob/master/save-points/00-Starting-point/BlazingPizza.Server/Startup.cs#L61. Sorry we missed that before.

**Comment by rysep2** [comment]
That worked, thanks!

**Comment by rynowak** [comment]
Leaving this issue open so we remember to add this line to the workshop.

**Comment by thangchung** [comment]
I followed the guidance above , but couldn't make it work. Don't know why :(

![image](https://user-images.githubusercontent.com/422341/59324279-5bbeda80-8d08-11e9-8802-ce3773d71e3b.png)

**Comment by camainc** [comment]
I'm trying to figure out how to debug client side, and I'm not getting very far. I can do the shift-alt-d thing in Chrome and open a debugging tab, and it looks like it should work, but no breakpoints are ever hit. I couldn't get the Edge/Dev browser to work at all.

I tried adding the "UseBlazorDebugging" method and it throws an exception:

Error CS1061 'IComponentsApplicationBuilder' does not contain a definition for 'UseBlazorDebugging' and no accessible extension method 'UseBlazorDebugging' accepting a first argument of type 'IComponentsApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

I'm using the very latest bits which I pulled down yesterday.

I know you guys are working very hard and I appreciate it. I just wish MS would throw more $$ at the Blazor client-side debugging experience. This is really needed to try to get any real work done using Blazor.

**Comment by rynowak** [comment]
Closing this as we've done the updates to the workshop. @camainc (or anyone else for that matter) - if you're having problems still, I'd suggest opening an issue on https://github.com/aspnet/AspNetCore/issues where we track work on the Blazor product.
