### ISSUE TITLE
Typo on line 76

### ISSUE THREAD

**Issue by wgrs** [dotnet-presentations/blazor-workshop#78]
var newOrderId = wait HttpClient.PostJsonAsync<int>("orders", OrderState.Order);
Blazing Pizza.Client Pages Index

**Comment by mattferderer** [comment]
Just noticed this as well when trying to launch. Saw `wait` instead of `awaited` & was confused.

**Comment by rynowak** [comment]
Thanks for the report. this has been fixed.
