### ISSUE TITLE
OrdersController PlaceOrder does not return OrderId in save-point 00

### ISSUE THREAD

**Issue by nckl** [dotnet-presentations/blazor-workshop#79]
I am following allow the tutorial adding adding all code to the save-point 00 set of projects. When attempting to follow the instructions for https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/03-show-order-status.md#automatically-navigating-to-order-details the application throws an error because the Orders Controller method PlaceOrder does not return the OrderId. Would you please consider returning the OrderId in save-point 00 - 02

This appears to be related to https://github.com/dotnet-presentations/blazor-workshop/issues/71

Thank you.

**Comment by rynowak** [comment]
This has been fixed. Thanks for the report.
