### ISSUE TITLE
Update to preview 6 and new auth features

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet-presentations/blazor-workshop#84]
I'm not sure if the updated tooling will be shipped early enough to use preview 6 for NDC Oslo, but if it is, we can switch over to the built-in auth features. If we change to a redirection flow instead of the popup, most of the code will disappear entirely.

We can keep the popup if we want, but that will involve retaining more of the custom code.

**Comment by rynowak** [comment]
Closing because this is done. Thanks @SteveSandersonMS
