### ISSUE TITLE
Live-reload on this workshop projects

### ISSUE THREAD

**Issue by thangchung** [dotnet-presentations/blazor-workshop#92]
I just wondering that how can we do the live-reload feature which is really important when we do a front-end development. Could we use `dotnet watch run` command on the Server project? I have tried it, but it was not working.

**Comment by peterblazejewicz** [comment]
Hey, what was the problem you've faced? On some setups the watch task needs update:
#121

**Comment by rynowak** [comment]
Closing this as it's not feedback on the workshop. Live-reload for ASP.NET Core in general is being worked on for .NET 5.
