### ISSUE TITLE
DeliveryLocation is null resulting in an error

### ISSUE THREAD

**Issue by JeroenvdBurg** [dotnet-presentations/blazor-workshop#95]
in the latest .net core 3 preview 6 version, the delivery location is added as an Owned type.  When I run it (both Src or save points) the DeliveryLocation is saved to the database, but with retrieving the orders (for the myorder overview or detail screen) the deliveryLocation property stays null resulting in an error. 

When I explicitly include the DeliveryLocation in the query in the ordersController ( .Include(o => o.DeliveryLocation) it works. 

Not sure if anyone else experience this also ?

**Comment by giggio** [comment]
Yes, I am having the same problem.

**Comment by danroth27** [comment]
Everything should be working now with the latest bits and workshop updates. Let us know though if you're still hitting issues!
