### ISSUE TITLE
Just pulled the update, will not build

### ISSUE THREAD

**Issue by baquick** [dotnet-presentations/blazor-workshop#97]
Just pulled the latest, into a clean/newly created folder.   Will not build.  I can confirm Preview6 nuget packages are referenced.

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	4	

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	12	

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	20	

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	28	

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	36	

Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ1031	The tag helper 'InputText' must not have C# in the element's attribute declaration area.	BlazingPizza.Client	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Client\Shared\AddressEditor.razor	44

**Comment by RafaDom** [comment]
Hello baquick - Double check you installed the proper preview-6  SDK 

https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by baquick** [comment]
I had, but I tried it again and now it working.  Something must have went wrong with first install attempt.

**Comment by hunborey0011-cell** [comment]
KEVSOKSAVOUN
