### ISSUE TITLE
Not a responsive designed site?

### ISSUE THREAD

**Issue by baquick** [dotnet-presentations/blazor-workshop#98]
Is it just me, or is this not a responsive designed site?   When I view it in Chrome in Responsive mode it is not able to display the pizza choices properly and the top nav does not fit.

**Comment by neven10** [comment]
Does it even matter? This is an example app . No one is going to test how it looks on various devices or if pizza can have nails as toppings , thats not the point.

**Comment by baquick** [comment]
Yes it matters.  I have watched the presentations and heard numerous times in the presentations "Modern web applications for modern browsers".   Guess what, a modern web app is responsive.   And guess what, I checked.   So I would classify this as not a modern web app for modern browsers and question whether blazor can do it or not.   This is an example app of what can be done with Blazor is it not?   If it's not an example of what can be done with Blazor than what is it?   Isn't Blazor supposed to be the next Client Side Framework for the future?  And we can't even get a demo that is responsive, why even put it out there then?   This is one of the first things folks looking into Blazor are going to experience and they and I are having an experience that doesn't support a responsive design.  Just little old me thinks this is very short sighted to put out a demo for modern web browsers and modern client side development, using the latest and greatest framework that is not responsive.

**Comment by neven10** [comment]
Cool. Fix css , do pull request.  It's open source after all.

**Comment by RafaDom** [comment]
I won't consider this an "Issue" but a "nice to have"

**Comment by kleinkauff** [comment]
Idk but maybe you are mixing some different concepts here. Blazor still are a framework for "Modern web applications for modern browsers" this was not to do with css and responsiveness.  As @RafaDom pointed this is not an issue

**Comment by menasheh** [comment]
CSS changes required for responsiveness have absolutely nothing to do with blazor.

**Comment by baquick** [comment]
I get all that.

But think of the C-levels that one might be presenting the latest sample framework project to, and they ask, is it responsive, because all our sites are today.

And I have to say, “this sample is not, but trust me, it’s just some CSS”….

They won’t get it.

What I don’t get, is why anyone or anyone group, would make the decision to put a sample together, and not take the effort to make it responsive….I can’t connect the dots on that…

Anyway…moving on….

**Comment by danroth27** [comment]
@stevesandersonms Thoughts on this?

**Comment by SteveSandersonMS** [comment]
It wasn't a design goal, but if someone wants to contribute an improvement, and they can do so in a sufficiently clear, simple, and high-quality way, that would be great.

**Comment by SteveSandersonMS** [comment]
It's been a few months, so I'll close this.

If someone is interested in providing a responsive design for this sample site, please let us know.
